
  
# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_Submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auto update submodule
        run: |
         git config --global user.email "tamgiangbui@gmail.com"
         git config --global user.name "silent1603"
         git submodule update --remote --merge  
       
  build_Linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run shell script
        run: |
         sudo apt-get update
         sudo apt install -y libx11-dev  libxext-dev  libglu1-mesa-dev freeglut3-dev mesa-common-dev libudev-dev libxrandr-dev 
         bash ./build.sh
  build_Window:
      runs-on: windows-latest
      steps: 
       - uses: actions/checkout@v2
       - name: setup-msbuild
         uses: microsoft/setup-msbuild@v1.1
       - name: run batch scripts
         shell: cmd
         run: |
          build.bat
       - name: build
         shell: cmd
         run: |
          cd build
          msbuild TinySFML.sln
         
